SELECT
    p.S_INFO_WINDCODE AS stock_code,
    p.TRADE_DT AS trade_date,
    p.S_DQ_AMOUNT AS amount,
    d.S_VAL_MV AS total_market_cap
FROM dbo.ASHAREEODPRICES p
LEFT JOIN dbo.ASHAREEODDERIVATIVEINDICATOR d
  ON d.S_INFO_WINDCODE = p.S_INFO_WINDCODE
 AND d.TRADE_DT = p.TRADE_DT
WHERE p.TRADE_DT BETWEEN ? AND ?
  AND p.S_INFO_WINDCODE IN ({stock_code_placeholders})
ORDER BY p.S_INFO_WINDCODE, p.TRADE_DT;
