SELECT
    INDUSTRIESCODE AS citic_l1_code,
    INDUSTRIESNAME AS citic_l1_name,
    LEVELNUM,
    USED
FROM dbo.ASHAREINDUSTRIESCODE
WHERE INDUSTRIESCODE LIKE ?
  AND LEVELNUM = ?
  AND USED = 1
ORDER BY INDUSTRIESCODE;

